dist: xenial
language: python
python:
  - 3.7

install:
  - pip install ansible-lint yamllint

script:
  - yamllint .
  - ansible-lint -c .ansible_lint playbook.yml

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
