- hosts: all
  remote_user: root
  vars_files:
    - defaults/basic.yml
    - defaults/advanced.yml
    - defaults/rules.yml
  vars:
    ansible_python_interpreter: python3

  tasks:
    - import_tasks: tasks/preflight.yml

    - name: Check if v2ray installed
      stat:
        path: /usr/bin/v2ray/v2ray
      register: v2ray_installed

    - include_tasks: tasks/v2ray_install.yml
      when: v2ray_installed.stat.exists == false

    - import_tasks: tasks/v2ray_configure.yml

    - import_tasks: tasks/iptables.yml

    - import_tasks: tasks/healthcheck.yml

  handlers:
    - name: restart v2ray
      systemd:
        enabled: true
        name: v2ray
        state: restarted

    - name: flush iptables
      shell: flush-iptables.sh

    - name: apply static ip
      reboot:
        reboot_timeout: 300
