- hosts: all
  remote_user: root
  vars_files:
    - defaults/basic.yml
    - defaults/advanced.yml
    - defaults/rules.yml
    - defaults/raw.yml
  vars:
    ansible_python_interpreter: python3

  tasks:
    - import_tasks: tasks/preflight.yml
    - import_tasks: tasks/v2ray_install.yml
    - import_tasks: tasks/v2ray_configure.yml
    - import_tasks: tasks/iptables.yml
    - import_tasks: tasks/healthcheck.yml
    - import_tasks: tasks/statistics.yml
    - include_tasks: tasks/dnsmasq.yml
      when: dnsmasq_enabled

  handlers:
    - name: restart v2ray
      systemd:
        enabled: true
        daemon_reload: true
        name: v2ray
        state: restarted

    - name: restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted

    - name: restart cron
      systemd:
        name: cron
        state: restarted

    - name: flush iptables
      shell: flush-iptables.sh

    - name: collect stats
      shell: collect-stats.sh
