- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: "{{ 'present' if dnsmasq_enabled else 'absent' }}"

- name: Generate dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 0644
  notify:
    - restart dnsmasq
