- name: Generate healthcheck script
  template:
    src: healthcheck.sh.j2
    dest: /usr/local/sbin/healthcheck.sh
    mode: 0755

- name: Add healthcheck to crontab
  cron:
    name: healthcheck
    job: /usr/local/sbin/healthcheck.sh 2>>/var/log/healthcheck.log
    minute: "*"
    disabled: "{{ not healthchecks_uuid == '' }}"
