- name: Generate static ip configure script
  template:
    src: ensure-static-ip.sh.j2
    dest: /usr/local/bin/ensure-static-ip.sh
    mode: 0755

- name: Configure static ip address
  shell: ensure-static-ip.sh
  register: static_ip
  changed_when: "'activated' in static_ip.stdout"

- name: Enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Disable all ipv6
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "{{ disable_all_ipv6 }}"
    sysctl_set: true
    state: present
    reload: true

- name: Stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
