- name: Configure static ip address
  script: ensure-static-ip.sh
  register: static_ip
  changed_when: "'CHANGED' in static_ip.stdout"
  notify: apply static ip

- name: Trigger handlers
  meta: flush_handlers

- name: Enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Stop systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
