- name: Make a copy of the outbounds variable
  set_fact:
    v2ray_processed_outbounds: "{{ v2ray_outbounds }}"

- name: Add the default tag into outbounds
  set_fact:
    v2ray_processed_outbounds: "{{ v2ray_processed_outbounds | combine(outbound, recursive=true) }}"
  vars:
    outbound: "{ '{{ item.key }}': { 'tag': 'forward-{{ item.key }}' } }"
  with_dict: "{{ v2ray_processed_outbounds }}"
  when: item.value.tag is not defined

- name: Add the default settings into outbounds
  set_fact:
    v2ray_processed_outbounds: "{{ v2ray_processed_outbounds | combine(outbound, recursive=true) }}"
  vars:
    outbound: "{ '{{ item.key }}': {{ v2ray_outbound_defaults }} }"
  with_dict: "{{ v2ray_processed_outbounds }}"

- name: Generate v2ray config file to remote
  template:
    src: config.json.j2
    dest: /tmp/v2ray-config.json
    mode: 0644
  register: generate_v2ray_config

- name: Validate v2ray configuration
  shell: "v2ray -test -config {{ generate_v2ray_config.dest }}"
  changed_when: false

- name: Ensure config dir exists
  file:
    path: /etc/v2ray
    state: directory
    mode: 0755

- name: Copy config file after validation passed
  copy:
    remote_src: true
    src: "{{ generate_v2ray_config.dest }}"
    dest: /etc/v2ray/config.json
  notify:
    - restart v2ray

- name: Trigger handlers
  meta: flush_handlers

- name: Ensure v2ray service is running
  shell: service v2ray status
  changed_when: false
  args:
    warn: false
