- name: Ensure installation directory exists
  file:
    path: "{{ v2ray_install_path }}"
    state: directory
    mode: 0755

- name: Extract v2ray archive
  unarchive:
    src: "{{ v2ray_archive }}"
    dest: "{{ v2ray_install_path }}"

- name: Validate v2* executable files
  shell: "{{ v2ray_install_path }}/v2ctl {{ v2ray_install_path }}/{{ item }}"
  changed_when: false
  loop:
    - v2ray
    - v2ctl

- name: Create symlinks to v2* executable files
  file:
    src: "{{ v2ray_install_path }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - v2ray
    - v2ctl

- name: Generate systemd service file
  template:
    src: v2ray.service.j2
    dest: /etc/systemd/system/v2ray.service
    mode: 0644
