- name: Copy v2ray binary to remote
  copy:
    src: "{{ v2ray_archive }}"
    dest: /tmp/v2ray.zip

- name: Download v2ray install script
  get_url:
    url: https://install.direct/go.sh
    dest: /usr/local/bin/
    mode: 0755

- name: Install v2ray
  shell: go.sh --local /tmp/v2ray.zip
  register: v2ray_install
  changed_when: true

- name: Print install result
  debug:
    var: v2ray_install
